name: msginf
services:
  msginf:
    container_name: msginf
    image: msginf:latest
    ports:
      - "8080:8080"
    depends_on:
      - activemq
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - msginf_network

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - "3306:3306"
    networks:
      - msginf_network
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'msginfdb'

  activemq:
    container_name: activemq
    image: islandora/activemq:3.1.1-amd64
    ports:
      - "61616:61616"
      - "8161:8161"
    restart: on-failure
    networks:
      - msginf_network

  kafka:
    image: apache/kafka:3.7.0
    hostname: kafka
    container_name: kafka
    networks:
      - msginf_network
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  kafka-ui:
    image: provectuslabs/kafka-ui
    hostname: kafka-ui
    container_name: kafka_ui
    networks:
      - msginf_network
    depends_on:
      - kafka
    ports:
      - 8081:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
      KAFKA_CLUSTERS_0_METRICS_PORT: 19101

networks:
  msginf_network:
    name: msginf_docker_net